version: '3.9'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build: .
    image: rest-go-api:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    depends_on:
      - postgres

volumes:
  data:
