definitions:
  request.CreateProductRequest:
    properties:
      company:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  request.UpdateProductRequest:
    properties:
      company:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  response.CreateProductResponseSwagger:
    properties:
      data:
        $ref: '#/definitions/schemas.ProductResponse'
      message:
        type: string
    type: object
  response.DeleteProductResponseSwagger:
    properties:
      data:
        $ref: '#/definitions/schemas.ProductResponse'
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  response.FindByIdProductResponseSwagger:
    properties:
      data:
        $ref: '#/definitions/schemas.ProductResponse'
      message:
        type: string
    type: object
  response.FindProductResponseSwagger:
    properties:
      data:
        $ref: '#/definitions/schemas.ProductResponse'
      message:
        type: string
    type: object
  response.UpdateProductResponseSwagger:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.ProductResponse'
        type: array
      message:
        type: string
    type: object
  schemas.ProductResponse:
    properties:
      company:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        type: string
      name:
        type: string
      price:
        type: number
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Listing products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FindProductResponseSwagger'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Find product
      tags:
      - Products
  /create:
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateProductResponseSwagger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Create product
      tags:
      - Products
  /delete:
    delete:
      consumes:
      - application/json
      description: Delete a   product
      parameters:
      - description: 'Product identification '
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.DeleteProductResponseSwagger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Delete product
      tags:
      - Products
  /find:
    get:
      consumes:
      - application/json
      description: Find by id product
      parameters:
      - description: 'Product identification '
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FindByIdProductResponseSwagger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: FindById product
      tags:
      - Products
  /update:
    put:
      consumes:
      - application/json
      description: Update a product
      parameters:
      - description: Product indentification
        in: query
        name: id
        required: true
        type: string
      - description: Request body to update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateProductRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/response.UpdateProductResponseSwagger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Update product
      tags:
      - Products
swagger: "2.0"
